### ISSUE TITLE
Standardized naming convention for feature branches?

### ISSUE THREAD

**Issue by J-Rose** [shirtsgroup/InterMol#109]
Since we've now adopted a new git workflow (http://nvie.com/posts/a-successful-git-branching-model/), I was wondering if we were concerned about establishing a naming convention for feature branches. The workflow doesn't specify, so long as they don't conflict with the core branches (master, develop).

Would we stick to the common iss##, relating each feature branch to a single issue, or do we want to use a different system?

**Comment by ctk3b** [comment]
Use default git-flow names: master, develop, feature/lammps, feature/desmond etc.
