### ISSUE TITLE
first force entry vs last force entry

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/InterMol#121]
The current rewrite (potentially the previous one as well) doesn't handle duplicated entries in the gromacs .top well.  Right now, it takes only the _first_ _seen_set of parameters for a bond.  However, gromacs itself uses the _last_ _seen_set of parameters for a bond. So if we take any duplicate set and reduce it to a single parameter. we should take the last one, as that is more gromacsian.  

This behavior should be verified, perhaps with an additional unit test.

Probably can be done with careful thinking about the .add command when the new force is added.

**Comment by ctk3b** [comment]
Need to double check if this is still happening in the re-write.
