### ISSUE TITLE
Separating out the transformation to the canonical form

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/InterMol#137]
I've checked in a new idea in a new branch 'canonical' that I think will help simplify some of the logic for transformations.

As you know, we've worked out a way to read and write over loops of parameter arrays, such that the order of the parameter is defined in forcedata.py for all programs.  Parameters are now also dictionaries to make some of this easier.

The problem is that frequently there are transformations (like multiplying force coefficients by 0.5 or 2 that are needed to change to a the 'canonical' form of the force.

1. Identify the force type from the text string in the file (using a predefined dictionary)
2. Read the parameters into a parameter dictionary from the file 
3. Convert the parameters to the canonical form
4. Create the force type

3. Is the key new step.  All of the transformations are put there, so that all of these transformations are kept in a angle place.

Note that I've organized it with the canonical transfer function having two modes -- into, and from.  This makes sure all the logic mapping in both directions is in the same place.

Gromacs is pretty much entirely in this new form, and appears to be working (at least, Gromacs->Gromacs is working! Note that I've updated to Gromacs 5.0). Take a look over that code and see if it makes sense.

I have lammps mostly in this form, but not quite yet -- dihedrals and impropers are not quite working correctly.  Note that I'm storing the impropers in the dihedral objects, but on printing out, the list gets looped through twice and the impropers and dihedrals are separated.

Note that now the only things that would need to be done to add an interaction are to modify a few lines in forcedata.py, add the appropriate entry in a couple of dictionaries at the start of each parser and run make_forces.  

To be able to convert the interaction into equivalent versions that do not have the same parameter name, or where the parameter name means something slightly different, one would have to edit the appropriate canonical_X function in the parser. 

Let me know if you have any questions about this!  A lot to wrap ones mind around, and the commenting still needs to be better.

I suspect this could all be done more cleanly, but bit at a time.  I think that this general organization will make it even easier to add new force terms.

**Comment by ctk3b** [comment]
This is more or less done but could use a writeupon the docs!
