### ISSUE TITLE
Likely naive installation issue

### ISSUE THREAD

**Issue by evanfeinberg** [shirtsgroup/InterMol#142]
Dear InterMol developers, 

It is wonderful that you all have created this much-needed project. I am quite new to molecular simulation, and have come across a problem that InterMol should be able to solve. I have a chemical system involving a membrane protein in solvent that I have generated with a few Schrödinger/Desmond tools, from protein preparation down to force field paramater assignment with Viparr, encapsulated in a .cms file. I would like to run a simple MD simulation in GROMACS using the system that was setup with Desmond tools. So it seems that I should use InterMol to convert the .cms to .gro and .top files compatible with GROMACS.

I downloaded the zip from GitHub and installed with the command "python setup.py install" in the "testing" directory. It seemed to install without a hitch. I then ran the given test command in the readme, "python convert.py --des_in /Users/evan/Downloads/InterMol-master/testing/inputs/Desmond/UnitTest/frag_opls2001/frag_opls2001.cms --gromacs --odir /users/evan/documents/schrodinger -e". While it did output two files, it also generated a bevy of errors, most of which are of form: 

"Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/intermol-0.1_dev-py2.7.egg/intermol/desmond_extension/desmond_parser.py", line 607, in load_ffio_block
    dihedralmatch.sum_parameters(newDihedralForce)
AttributeError: 'bool' object has no attribute 'sum_parameters'
"

Any idea what this means? Did I make some basic error in either installation or execution? 

Thank you in advance for any help!!

Best regards,
Evan

**Comment by mrshirts** [comment]
Am closing because so much has changed and most of these issues have be addressed (and others now have specific issues)
