### ISSUE TITLE
py.test not working?

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/InterMol#146]
Following the instructions here:

http://intermol.readthedocs.org/en/develop/installation.html

it says to go into the base directory and run py.test, but that doesn't seem to work.  I tried the InterMol, the intermol, and the tests directory.  I installed pytest in case that was required, but it still doesn't work.  In all cases, the error is

  py.test: Command not found.

**Comment by ctk3b** [comment]
Is his on develop?

**Comment by ctk3b** [comment]
Although if the command wasn't found then it sounds like pytest was not installed correctly.

**Comment by ctk3b** [comment]
That aside now that mentioned that page on the docs, I also need to update that section to explain running individual tests.

**Comment by mrshirts** [comment]
It appears to be an install error; I corrected it, but am still having issues:

Traceback (most recent call last):
  File "/usr/bin//py.test", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/usr/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: pytest==2.6.4

Not sure why, since it should be pytest==2.6.4: in the pip install it showed:
   Collecting pytest
      Downloading pytest-2.6.4.tar.gz (512kB)

**Comment by ctk3b** [comment]
Is this working for you now?

This isn't directly related but I switched over to [anaconda](https://store.continuum.io/cshop/anaconda/) and their [virtualenv and install system](http://www.continuum.io/blog/conda) a few months ago and it's been absolute bliss.

**Comment by ctk3b** [comment]
I think this can be closed now.
