### ISSUE TITLE
Dihedrals in Gromacs -> Gromacs not matching

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/InterMol#147]
This was previously reported on the "develop" code.

**Comment by mrshirts** [comment]
The reason is that some dihedrals are being created multiple times, which leads to duplicates on the writing, which leads to incorrect energies.  I'm not yet sure why.  All the parameters appear to be correct.

Specifically, the two dihedrals, in 'micelle'  test case:

       6       7       8       9     3    9.27890000e+00    1.21560000e+01   -1.31200000e+01   -3.05970000e+00    2.62400000e+01   -3.14950000e+01
      14      15      16      17     3    9.27890000e+00    1.21560000e+01   -1.31200000e+01   -3.05970000e+00    2.62400000e+01   -3.14950000e+01

Are created multiple times.  It's not clear why these two are special -- there are other parameters with the same types.  still investigating.

**Comment by mrshirts** [comment]
Figured it out.  Problem is in create_dihedrals.

     btypes = [self.lookup_atom_bondingtype(int(x))
     	                      for x in dihedral[:n_atoms]]

Can return multiple types if there are multiple matches which can happen if there are wildcards.  All get added.  

For example, in 'micelle' test case, we have dihedral: 

['6', '7', '8', '9', '3']

With btypes:

['ETS', 'CP2', 'CP2', 'CP2']

here we get two matches:

[TrigDihedralType(bondingtype1=X, bondingtype2=CP2, bondingtype3=CP2, bondingtype4=X, fc0=12.5589 kJ/mol, fc1=9.82315 kJ/mol, fc2=6.56 kJ/mol, fc3=10.6071125 kJ/mol, fc4=3.28 kJ/mol, fc5=1.9684375 kJ/mol, fc6=0.0 kJ/mol, improper=False, phi=0 deg), TrigDihedralType(bondingtype1=X, bondingtype2=CP2, bondingtype3=CP2, bondingtype4=X, fc0=12.5589 kJ/mol, fc1=9.82315 kJ/mol, fc2=6.56 kJ/mol, fc3=10.6071125 kJ/mol, fc4=3.28 kJ/mol, fc5=1.9684375 kJ/mol, fc6=0.0 kJ/mol, improper=False, phi=0 deg)]

I'll let Christoph address it, since he knows the current logic better.  If this code is supposed to return multiple values, then if the length is greater than 1, we can convert list(set(dihedral_types)), and just get the unique values.  If it isn't supposed to return multiple values, then breaking when the first match is found could be done.

**Comment by ctk3b** [comment]
Good catch! This was written to allow for one set of 4 atoms to return multiple dihedraltypes but I didn't properly address all the wildcard issues. Dihedraltypes are now aggregated in a set and then returned as a list. 

Both micelle tests run. The last remaining test is 2PPN which is because of #152
