### ISSUE TITLE
Issues with Gromacs->Lammps dihedrals (feature/lammps)

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/InterMol#149]
Haven't had a chance to fully debug it, but it appears to be because multi/harmonic is defined differently than RB in Gromacs.  In gromacs, it's sums of powers of cos(phi-180), whereas in lammps it's sums of powers of cos(phi).  This means that the odd powers should have differing signs after conversion, but they do not.  

For the bond 1 case, we have:

Gromacs:

     2       1       4       5     3    1.88280    5.64840    0.00   -7.531200    0.00    0.00

Lammps (which is dihedral type 9 in the converted file):

     9 multi/harmonic    4.500e-01    1.350e+00    0.0e+00   -1.80e+00    0.0e+00

Note they are only different by 4.184, instead of having any different minus signs (for the 2nd and 4th coefficients). It likely involves lammps printing, although might involve gromacs reading, since gromacs could be both reading in and reading out incorrectly, canceling each other.

**Comment by mrshirts** [comment]
Note that this was handled at one point in the past (likely the Aug 9th version), but may have been lost at some point.

**Comment by ctk3b** [comment]
Hmm the minus signs are added by changing phi=0 to 180 and vice versa. Maybe it's happening twice. I'll take a look after the duplicate dihedral issue.

**Comment by mrshirts** [comment]
Just to be clear - it happens differently in gromacs and lammps, so if gromacs should do the minuses on read, and lammps not on write (or visa versa depending on what the canonical form is)

**Comment by ctk3b** [comment]
Yeah the lammps parser does something here to change the sign convention https://github.com/shirtsgroup/InterMol/blob/feature/lammps/intermol/lammps/lammps_parser.py#L178

but there's also a general conversion happening here 
https://github.com/shirtsgroup/InterMol/blob/feature/lammps/intermol/forces/convert_dihedrals.py#L192

Like you said, presumably something is happening twice when it shouldn't.

**Comment by ctk3b** [comment]
This particular issue should be fixed on the `forcetype` branch.
