### ISSUE TITLE
Support lookup for dihedrals defined with macros

### ISSUE THREAD

**Issue by ctk3b** [shirtsgroup/InterMol#152]
E.g. in the 2PPN stress test `10    12    14    16    3    dih_VAL_chi1_N_C_C_C` needs to pull the correct parameters from `oplsaa.ff`

**Comment by mrshirts** [comment]
I think the cleanest way to deal with this is to replace includes and defines recursively in reading in gromacs, like the C preprocessor does. That's exactly how it is handled in gromacs and in earlier versions of the parser. I.e. These are #defines that are in the #include files. If we are using simtk parsers for this and they don't support it, then that is functionality they need!

**Comment by ctk3b** [comment]
This is currently read into self.defines but we need to add functionality to parse those defines. Right now
they are of the form:
```
{'improper_Z_CM_X_Y': '180.0     62.76000   2', 
'dih_dicarboxylicacid_C_CT_CT_HC': '0.15481   0.46442   0.00000  -0.61924   0.00000   0.00000',
...
```

**Comment by ctk3b** [comment]
Looks like I had done some scratch work already:
https://github.com/shirtsgroup/InterMol/blob/develop/intermol/gromacs/gromacs_parser.py#L933

**Comment by ctk3b** [comment]
So this actually seems to be implemented already but there's some issue with the dihedral conversion. I'll open a new issue for the 2PPN test case
