### ISSUE TITLE
Get the 2PPN test case working for gromacs-to-gromacs (dihedral issue)

### ISSUE THREAD

**Issue by ctk3b** [shirtsgroup/InterMol#153]
Currently 4788 dihedrals get read in and 5977 get read out. As far as I can tell (please double check me), there are only dihedrals of type 1 and 3, none of which need to be decomposed.

**Comment by mrshirts** [comment]
Seems to be an issue in lookups and wildcards in create_dihedrals. For the lookup:

     ['H', 'N', 'CT_2', 'HC']

The result is: 

     [TrigDihedralType(bondingtype1=H, bondingtype2=N, bondingtype3=CT_2, bondingtype4=HC,    fc0=0.0 kJ/mol, fc1=-0.0 kJ/mol, fc2=0.0 kJ/mol, fc3=-0.0 kJ/mol, fc4=0.0 kJ/mol, fc5=-0.0 kJ/mol, fc6=0.0 kJ/mol, improper=False, phi=0 deg), TrigDihedralType(bondingtype1=H, bondingtype2=N, bondingtype3=CT_2, bondingtype4=X, fc0=0.0 kJ/mol, fc1=-0.0 kJ/mol, fc2=0.0 kJ/mol, fc3=-0.0 kJ/mol, fc4=0.0 kJ/mol, fc5=-0.0 kJ/mol, fc6=0.0 kJ/mol, improper=False, phi=0 deg), TrigDihedralType(bondingtype1=H, bondingtype2=N, bondingtype3=CT_2, bondingtype4=X, fc0=0.0 kJ/mol, fc1=-0.0 kJ/mol, fc2=0.0 kJ/mol, fc3=-0.0 kJ/mol, fc4=0.0 kJ/mol, fc5=-0.0 kJ/mol, fc6=0.0 kJ/mol, improper=False, phi=0 deg)]

The last two of the three are identical, and those should be caught by using a set. The first one is different in that is the most specific form of the dihedral that the wild card catches, and the wildcard version is not needed.

It seems like it would be best to match to the dihedral w/o wildcards, and only after it doesn't match check for wildcards.

**Comment by ctk3b** [comment]
Ok so to clarify the intended behavior:

Gromacs will only try to match wild cards after not finding a type with all 4 bondingtypes?

I'm also staring at that same output right now and there's a bit of a weird issue because `H N CT_2 X` is defined twice in the forcefield file (opls.ff/ffbonded.itp). This leads to two unique objects being created in python which is again flirting with the equality issue...

**Comment by ctk3b** [comment]
The RB types that are defined multiple times in the forcefield are the biggest contributor to the energy difference right now (I kluged a uniqueness checker for trig dihedral types which brought it down to 0.067 from 18.02).

**Comment by mrshirts** [comment]
> Gromacs will only try to match wild cards after not finding a type with all 4 bondingtypes?

Correct. 

> I'm also staring at that same output right now and there's a bit of a weird issue because H N CT_2 X is defined twice in the forcefield file (opls.ff/ffbonded.itp). This leads to two unique objects being created in python which is again flirting with the equality issue...

Huh. Yeah, that's odd.  That looks like a typo.  I assume that gromacs is doing something like reading the last one, so it doesn't really matter as long as they are all the same.   So, probably gromacs is robust to multiple types, though it shouldn't create multiple dihedrals.  

But the file should just have one of each type, not multiples, even if multiple types don't cause problems.

**Comment by ctk3b** [comment]
Ok then maybe this is something worth mentioning to whoever curates the forcefield files for gromacs. The duplicates that I have found so far in opls:
`H N CT_2 X`
`CA CA CT X`

For our purposes though, we should probably filter them. I'll try to just get something working to see if that's the only issue and we can talk about refining it after.

**Comment by ctk3b** [comment]
Ok so I threw something together which will check trig and improper harmonic types for uniqueness before we use them to create a new dihedral. Since 
* everything gets converted to these types before this point in the code anyways
* dihedrals are the only place where we're currently allowing multiple types for the same set of bondingtypes (the key)

This may be an ok fix for now but we should probably write up exactly which cases grompp handles how so that we can be sure to cover all our bases.

There, however, still a 0.0015 energy differences somewhere else in the dihedrals.

**Comment by mrshirts** [comment]
> Ok then maybe this is something worth mentioning to whoever curates the forcefield files for gromacs. 

Redmine issue filed with Gromacs.  There are about 90 in the oplsaa.ff nonbondeds.

**Comment by mrshirts** [comment]
> There, however, still a 0.0015 energy differences somewhere else in the dihedrals.

Interesting.  The number and ordering of the dihedrals seem to be correct, and the parameter seem to be the same (both inputs and outputs are the same, as the functional form is the same.  Not sure if round-off error could explain, or if there is something else going on.

**Comment by ctk3b** [comment]
This is now working correctly for me. Closing for now.
