### ISSUE TITLE
Error thrown on nonnumeric result for test_gromacs.

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/InterMol#170]
I'm getting the error at the very end of runnng 
Exception: Found non-numeric result for GROMACS to DESMOND. This probably means an error occured somewhere in the conversion.

(first, occured misspelled).

The conversions were all 'converted' or unsupported force errors (which are expected results), so exiting with an exception seems harsh to do here.

**Comment by ctk3b** [comment]
Ah yeah. I need to clean up the testing code a bit. I'll add this to the list.

**Comment by ctk3b** [comment]
Fixed in #177
