### ISSUE TITLE
Dihedral logic error in frag_opls2001

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/InterMol#172]
for frag_opls2001, for the dihedral with atoms == (81, 80, 83, 84), then only fc0 is nonzero. According to the logic of convert_dihedral_from_trig_to_proper, fc0 and one other angle should be nonzero.  Not clear where the error is coming -- likely reading in to the angle from test_desmond, I'm guessing.

**Comment by mrshirts** [comment]
More info:

When:

 self.create_forcetype(self.desmond_dihedrals[key], atoms, kwds)

is called with kwds = [-3.09, -3.09, 0, 0.0, -0.0, 0, 0, -0.0], then the phi is set to -3.09, rather than fc0 and fc1 being set to -3.09.  

I think one of the fundamental issues here is that instead of the values read from the text file being passed to the canonical_dihedral routine, a dihedral angle structure itself is passed, which means that some dihedral has to be created, which means that some level of parsing has to be done before the main level of parsing, and in this case, the parsing is incorrect.

I think it might be more self-contained if the parsing was entirely contained within the canonical_dihedral/angle/bond logic, rather than some having to be outside, and then more inside.

**Comment by ctk3b** [comment]
So to clarify, you are suggesting that the `canonical_XYZ` functions actually accept the parsed kwds and nothing else? Effectively removing any kind of `create_XYZ` functions? 

That makes sense to me but I would then suggest splitting the functions into `read_canonical_XYZ` and `write_canonical_XYZ`.

**Comment by mrshirts** [comment]
More along the lines that there would be a create_xyz function that would handle the parsing of the lines, but the logic of deciding which text correspond to which class goes somewhere else.  

We should probably talk about it. I have a workaround, but it's not great.

**Comment by ctk3b** [comment]
Yeah that makes sense. `canonical_XYZ` knows what to do with a given set of kwds and those kwds are produced by a text parsing function.

**Comment by mrshirts** [comment]
The particular bug fix is closed, though it requires assuming that phi is before fc0, fc1, etc, which should not be assumed (but that's for a larger rewrite).
