### ISSUE TITLE
Incorrect logic in gromacs dihedral read in conversion?

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/InterMol#174]
I noticed that the gromacs tests return a lot of warnings of the type:

Did not convert dihedral: <class 'intermol.forces.trig_dihedral_type.TrigDihedral'>

The issue seems to trace down to the logic in create_dihedral in gromacs_parser. Right now, create dihedral assigns the dihedral type by the code:

             if numeric_dihedraltype in ['1', '3', '4', '5', '9']:
                gromacs_dihedral = TrigDihedral
            else:
                gromacs_dihedral = self.gromacs_dihedrals[numeric_dihedraltype]

This dihedral then gets passed to canonical dihedral, where it goes through logic 

            if dihedral == ProperPeriodicDihedralType:
                convertfunc = convert_dihedral_from_proper_to_trig
                converted_dihedral = TrigDihedralType
            elif dihedral == ProperPeriodicDihedral:
                convertfunc = convert_dihedral_from_proper_to_trig
                converted_dihedral = TrigDihedral
            elif dihedral in (ImproperHarmonicDihedralType, ImproperHarmonicDihedral):
                convertfunc = convert_nothing
            elif dihedral == RbDihedralType:
                convertfunc = convert_dihedral_from_RB_to_trig

etc.  i.e. it's not expecting the dihedral to be converted to TrigDihedral yet, and ends up giving up when it finds a dihedral that is already converted. 

This is clearly duplicated logic, but I'm not sure exactly where to remove the duplication.

**Comment by ctk3b** [comment]
Fixed in #179
