### ISSUE TITLE
Custom Exceptions

### ISSUE THREAD

**Issue by ctk3b** [shirtsgroup/InterMol#180]
I think it would be nice to come up with a set of custom exceptions that we consistently use for InterMol specific problems. That way we can hopefully provide more useful output and ensure that our testing summaries are formatted nicely. 

#177 introduces `MultipleValidationErrors` as a convenience for the final output summary.

On my wish list are:
* `UnsupportedConversion`, for when users attempt A->B and a functional form is supported in package A but not B. This should accept as its arguments the unsupported functional and the program that doesn't support it.
* `UnimplementedConversion`, for things we intend to support but haven't implemented. Could have an optional argument referencing a github issue.
* `ParsingError`, for issues during reading

**Comment by mrshirts** [comment]
I agree that we need consistent exceptions across everything. 

I'd suggest UnsupportedConversion (instead of ImpossibleConversion), which takes arguments making it clear what program doesn't support the feature, and Unimplemented Conversion, which makes it clear that we haven't implemented it yet.

**Comment by ctk3b** [comment]
That makes more sense. Updated the original post to reflect your idea.

**Comment by ctk3b** [comment]
Implemented for now in #224.  Naming could potentially be improved.
