### ISSUE TITLE
error on energy evaluation in lammps?

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/InterMol#182]
Getting the following error on lammps writeout, again failing to remove a nonexistent file.  Relates to the fix for the nonexistent no file found in python 2.7?

INFO 2015-08-03 14:23:53 Evaluating energy of /Users/mrshirts/work/papers/MMTOOLS/InterMol/intermol/tests/unit_test_outputs/from_gromacs/angle1/angle1_converted.input
ERROR 2015-08-03 14:23:53 [Errno 2] No such file or directory: '/Users/mrshirts/work/papers/MMTOOLS/InterMol/intermol/tests/unit_test_outputs/from_gromacs/angle1/lammps_stdout.txt'
Traceback (most recent call last):
  File "/Users/mrshirts/work/papers/MMTOOLS/InterMol/intermol/convert.py", line 216, in main
    '{0}.input'.format(oname), lmppath=lmppath)
  File "/Users/mrshirts/work/papers/MMTOOLS/InterMol/intermol/lammps/lammps_driver.py", line 46, in lammps_energies
    os.remove(stdout_path)
OSError: [Errno 2] No such file or directory: '/Users/mrshirts/work/papers/MMTOOLS/InterMol/intermol/tests/unit_test_outputs/from_gromacs/angle1/lammps_stdout.txt'

**Comment by ctk3b** [comment]
Sorry, used the wrong error type. Should be fixed in 344af4f
