### ISSUE TITLE
Desmond -out.cms causing duplicated tests.

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/InterMol#186]
the desmond file x-out.cms is getting written back to the directory x.cms is from, resulting in an increasing number of .cms files being used in the test each time it's called. (x-out-out.cms, x-out-out-out.cms, etc).

**Comment by ctk3b** [comment]
Hmm I can't reproduce this behavior. What exactly are you running?

**Comment by mrshirts** [comment]
When Desmond runs on x.cms, it prints out a x-out.cms.  If that gets saved to the input file, it treat that cms as a new input.

**Comment by mrshirts** [comment]
I'll probably need to handle this because I have desmond running.

**Comment by ctk3b** [comment]
Oh I see this is the actual desmond output, not the output of intermol's desmond parser. That will have to be handled by the desmond driver.

**Comment by mrshirts** [comment]
Fixed by #189.  Note that the file can still be generated if desmond is stopped partway through running, which may need to be addressed at some point.
