### ISSUE TITLE
gromacs mdp rcoul set from 0.999990 to 1.999999?

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/InterMol#188]
Was wondering why gromacs mdp  rcoul was changed.  Any ideas?

**Comment by ctk3b** [comment]
We had emailed about this about a month ago. It allows the G/L comparison to match to within ~1e-7 without having to somehow account for the differences in long-range implementations.

Thinking back now though, was there an issue with desmond that did not allow any kind of calculations _without_ long-range electrostatics?

**Comment by mrshirts** [comment]
OK, I'll fiddle around with the other parameters to make sure they are consistent.

**Comment by ctk3b** [comment]
Can we close this? It sounds like we need somewhere to collect information about non-bonded calculations across different engines and nail down a scheme that works across all (or most) of them.

**Comment by mrshirts** [comment]
Yeah, I think this needs to be made more general, i.e. working out a
nonbonded scheme -- which I thought I had figured out at some point, but
clearly the documentation is not so great. i'll think about that tonight.
