### ISSUE TITLE
Figure out why spce1 in desmond is dying.

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/InterMol#197]
Failing with non-zero return code (so properly specified file, but dies).

**Comment by mrshirts** [comment]
spce1 is a box of water at uniform density.  When the box size was increased to 50.1, it became a nonuniform box of water and started having problems.

When run with a cutoff of 9 A, and reduced to the original box size of 20 A, it runs correctly.

**Comment by ctk3b** [comment]
Hmm why would this cause problems for a single point energy calculation?

**Comment by mrshirts** [comment]
Likely a problem of trying to figure out how to do the PME grid with a big chunk of water in the middle and empty space everwhere else, and failing.
