### ISSUE TITLE
lammps pairs1 nonbonded energies off

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/InterMol#198]
lammps pairs1 test is not being translated correctly. It appears to be the LJ 1-4 terms.  All bonded terms look fine.

**Comment by ctk3b** [comment]
The problem here is that pairtypes aren't getting written in LAMMPS. Going to be a little annoying to fix but shouldn't be too bad.

**Comment by mrshirts** [comment]
What information is needed for detection?  Any questions I can provide insight on?

**Comment by ctk3b** [comment]
Alright there were two problems:
1. Pairtypes weren't written at all (#218 fixes that).
2. LAMMPS does not allow specific atom pairs to have different parameters. The only way I can think of for doing this is to create whole new atomtypes... which sucks

**Comment by mrshirts** [comment]
If something isn't supported, then it's fine to mark something as not supported.  At this stage, we don't have to support converting all functionality; just make it clear which ones are supposed to work and which ones aren't.

**Comment by ctk3b** [comment]
Ok sounds good. I'll have the exceptions (#180) implemented later tonight and this will be a use case!

**Comment by ctk3b** [comment]
Closing in favor of more specific issue #219
