### ISSUE TITLE
pytest required

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/InterMol#208]
test_all.py now requires pytest, but that does not get installed by setup.py

**Comment by ctk3b** [comment]
This is somewhat of a personal preference call. Most packages that I've seen strictly include packages required to run the code when installed and this typically excludes testing functionality and things like documentation generation.

**Comment by mrshirts** [comment]
Yeah, I think that people will want to run test_all.py to make sure that it's working properly.  The documentation should already be generated, so that wouldn't be needed.

**Comment by ctk3b** [comment]
Added in #211
