### ISSUE TITLE
Gromacs not writing virtuals

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/InterMol#235]
Even though it passes the virtual check (because the virtual particles are defined and in the right place), virtual bonds themselves are not actually written out into gromacs files.

**Comment by ctk3b** [comment]
Is there a general way to test for this, e.g. from the energy/log outputs?

**Comment by mrshirts** [comment]
I'm going to play around with this a bit.  I think there may be (if I eliminate continuation = yes, then I _think_ the energies will only be right if the virtual is turned on, but it's probably a lower priority than getting the other bits right.  The only two supported programs that handle virtuals are gromacs and desmond, and they have the same functional forms (copied from gromacs, I think) so that functionality is fairly robust.

**Comment by ctk3b** [comment]
Virtual sites are currently NOT being read in by GROMACS. Looks like I started working on making it happen in the [forcetype branch](https://github.com/shirtsgroup/InterMol/blob/forcetype/intermol/gromacs/gromacs_parser.py#L1415).

This must have gotten lost during one of the re-writes (probably mine from last winter).

**Comment by mrshirts** [comment]
This is currently an issue with TIP4P water, so we should address it.

**Comment by ctk3b** [comment]
I believe this was fixed in #302. Closing for now
