### ISSUE TITLE
Support ParmEd conversions in convert.py

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/InterMol#243]
We could fairly easily support GRO<->AMBER by calling ParmEd in convert.py.  This might be a way to start integrating things a bit more.

More ambitiously; we could do AMBER->anything or anything->AMBER by converting through GRO via calling multiple conversions (AMBER->Gromacs->other things).

**Comment by ctk3b** [comment]
Implemented for amber and charm but we could probably generalize this a bit more in the future.
