### ISSUE TITLE
More than one {0} style found triggered too often?

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/InterMol#245]
In the lammps_parser, the warning:

            logger.warning("More than one {0} style found!".format(force_name))

Gets trigged a lot (hundreds of times for some files?) for dihedrals.  If it is actually allowed to have multiple styles as a general practice, perhaps this shouldn't be triggering?

**Comment by ctk3b** [comment]
Yeah this is a remnant from before I implemented multiple styles. As long as the output is correctly producing a "hybrid" style this should be removable.

**Comment by ctk3b** [comment]
Resolved by #248
