### ISSUE TITLE
ParmEd and intermol not playing well together; Gromacs saves as RB as default, which ParmEd doesn't like.

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/InterMol#262]
While using ParmEd to convert from Amber to Gromacs, it fails to convert back to AMBER because the GROMACS default gets saved as RB dihedrals (the most general form).  AMBER reads those in, but doesn't convert them to things it can use.  This isn't horrible, since we don't NEED to convert back to AMBER (you can convert just with ParmEd), but indicates something a little inconsistent about the interactions between the two programs. Just something to remember for now.

**Comment by swails** [comment]
Right, we talked about this over skype.  What I need to do is take your RB<==>Proper torsion conversion code and add that to ParmEd.  That's been on my list of things to do, but lack of time and reminders has pushed it down on my list :).

I'll add a ParmEd issue now and reference this issue.

**Comment by mrshirts** [comment]
Yeah, I think it's lower priority (maybe we wait until there is a bit more integration) but it would be a great thing to eventually have.

**Comment by ctk3b** [comment]
Resolved by https://github.com/ParmEd/ParmEd/issues/460
