### ISSUE TITLE
Not the ideal location for writing test output.

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/InterMol#275]
When running on an setup.py installed version of InterMol, the output files are written to:

$PYTHON_INSTALLATION_LOCATION/python2.7/site-packages/intermol-0.1.0.dev0-py2.7.egg/intermol/tests/unit_test_outputs/from_gromacs/[system name]/debug.log

This may not be the best place to write it to.   Is there a way we can reorganize so the test output is written locally? Perhaps it is written by default into the current directory, with output options given.  Might that work?

**Comment by ctk3b** [comment]
I believe this was fixed on the develop branch. I'll take a look at getting the pathing fixes ported back into master.

**Comment by mrshirts** [comment]
Ah, great.  I have one fix to check in for LAMMPS unit tests which I will try to get done tonight, though might collapse (Flew to Europe today, up for many hours).
