### ISSUE TITLE
Energy comparison between Gromacs and Desmond

### ISSUE THREAD

**Issue by Marcela51** [shirtsgroup/InterMol#289]
Hello when using the -e option with convert.py,
 python convert.py --gro_in nowater2.gro topol.top --desmond -e
I am getting:
libmkl_rt.so: cannot open shared object file: No such file or directory
I have defined:
source /opt/packages/gromacs-5.1.3/bin/GMXRC.bash
and have loaded the  module desmond:
/opt/modulefiles/desmond/2016.1:

setenv		 DESMOND_VERSION 4.5 
setenv		 DESMOND_DIR /opt/packages/Desmond_Maestro-2016.1 
prepend-path	 PATH /opt/packages/Desmond_Maestro-2016.1 
setenv		 LD_LIBRARY_PATH /opt/packages/Desmond_Maestro-2016.1/desmond-v4.5/lib/Linux-x86_64 
setenv		 SCHRODINGER /opt/packages/Desmond_Maestro-2016.1 
setenv		 VIPARR_FFDIR /opt/packages/Desmond_Maestro-2016.1/desmond-v4.5/data/viparr/ff 

Can you tell me what I am doing wrong? The conversion (without the -e option) works fine! thanks, Marcela

**Comment by mrshirts** [comment]
Marcela, can you let me know if, when you run the input and output files manually with Desmond and Gromacs, the energy terms match?  I'll investigate this after getting back tonight -- it's not an error that I have seen, but I can probably find it.

**Comment by Marcela51** [comment]
Thanks, I will. I think it is not finding the desmond install. 

Marcela

**Comment by mrshirts** [comment]
Hmm.  I wasn't able to get this to happen.   I assume if you run the output files manually using desmond, you are able to get the simulation to complete?  What was in stderr.

PATH="/home/mish4610/InterMol/:/home/mish4610/anaconda2/bin:/home/mish4610/software/install_gromacs/bin:$PATH"
export SCHRODINGER="/opt/schrodinger2016-1/"
export GMXDATA="/usr/local/gromacs/share/gromacs/"

**Comment by Marcela51** [comment]
thanks it works now, it was a matter of defining Desmond.
Does this mean all the parameters are in the converted cms file, and one
does not need to run “viparr” on Anton to add FF? Thanks a lot,
I have already built the info in our wiki with thanks to you and Christoph!

Below is what I get for the the tests/gromacs/stress_tests/2PPN_bulk/ example.
 Does it look OK? I am not getting Electrostatic for Desmond it seems.

Energy group summary
=======================================================================
                type     input(gromacs)  output (desmond)    diff (desmond)
               Angle      1387.81506348     1387.82698424        0.01192076
           Potential   -123226.33593750  -123259.88353280      -33.54759530
               LJ-14      2864.29467773     2864.29935977        0.00468203
          Coulomb-14     10350.23242188    10350.23271816        0.00029629
                Bond      2822.36132812     2822.36670509        0.00537696
       Electrostatic   -172436.11132812               n/a               n/a
       All dihedrals      1594.50995255     1594.50073525       -0.00921730

Input gromacs potential energy:       -123226.33593750
Difference in potential energy from gromacs=>desmond conversion:       -33.54759530


thanks again,
Marcela

**Comment by mrshirts** [comment]
> Does this mean all the parameters are in the converted cms file

Correct.  All the parameters need to be there, otherwise viparr with write them over with the ones it stored, which might not match the GROMACS parameters.

> Does it look OK? I am not getting Electrostatic for Desmond it seems.

Desmond does not separate electrostatic out, just reports overall long range interactions.  The different total energies are due to the fact that long range interactions are calculated slightly differently between the programs. The slight differences seen for all the other terms are the level of differences that we expect to see based on our other comparisons.

It would be great if you could also put in the wiki that people who use the code should cite: DOI: 10.1007/s10822-016-9977-1

If you have any other example files, please send them to us to look at, to try to ferret out any other errors; I'm sure people will find something in their conversion work, and they should file issues which we will address

**Comment by Marcela51** [comment]
thank you,
Right now I do not have any other examples, if I get to prepare more I will make sure to share.

So the way I undestand it, we will use InterMol to convert to cms on a cluster called Kollman
(I guess you are familiar with the Anton environment at PSC), 
and then convert to dms and run viparr on Anton2. The format that viparr produces
on Anton2 might be slightly different than the one produced by desmond, and there are force
fields on Anton2 that are not on desmond. Does this sound like a good plan?

thanks again,

Marcela

**Comment by mrshirts** [comment]
Hmm. I'm not sure what viparr would be doing in this case.  My understanding is that all of the interaction parameters will already be defined in the cms (and then DMS).   Otherwise, one would get a file that wouldn't actually match the energies of what the GROMACS file was.

**Comment by Marcela51** [comment]
thanks, 

Marcela

**Comment by mrshirts** [comment]
THough of course, you should verify that the .dms that runs on Desmond also does run on Anton2.  I assume so, but better to verify.

**Comment by mrshirts** [comment]
One other thing -- you probably will need to adjust the setting that would go in the .cfg. The one provided in the tests is one that is a good match for GROMACS energies, but won't necessarily run on Anton2
