### ISSUE TITLE
installing InterMol

### ISSUE THREAD

**Issue by Marcela51** [shirtsgroup/InterMol#291]
Hello I am running into a problem when installing InterMol on the machine that 
we will be using for the workshop.

Here is what I did:
on the InterMol directory:
pip install --editable .

This installed InterMol successfully. Then 
on the python/2.7.8 directory:
git clone -b amber_vels https://git@github.com/ctk3b/ParmEd.git
cd ParmEd
pip install --editable .

Everything worked fine. But then I went into the InterMol directory and 
typed git pull
when trying to run I get the following error:

[mmadrid@kollman0 Kubo_Lin]$ python /usr/local/packages/InterMol/intermol/convert.py --gro_in 1us.gro mix.mdp --desmond -e
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=nr
    --max-age=epoch
    --min-age=epoch
    --sparse
    --no-merges
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --abbrev=nr | --no-abbrev
    --abbrev-commit
    --left-right
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all
Traceback (most recent call last):
  File "/usr/local/packages/InterMol/intermol/convert.py", line 8, in <module>
    import parmed
  File "/usr/local/packages/python/2.7.8/ParmEd/parmed/__init__.py", line 18, in <module>
    __version__ = get_versions()['version']
  File "/usr/local/packages/python/2.7.8/ParmEd/parmed/_version.py", line 485, in get_versions
    pieces = git_pieces_from_vcs(cfg.tag_prefix, root, verbose)
  File "/usr/local/packages/python/2.7.8/ParmEd/parmed/_version.py", line 284, in git_pieces_from_vcs
    pieces["distance"] = int(count_out)  # total number of commits
TypeError: int() argument must be a string or a number, not 'NoneType'

I am hopping I am doing something stupid. Can you send me some instructions? thanks a lot, Marcela

**Comment by ctk3b** [comment]
Ah that's the same issue as #284  - the hacky fix is to comment out the lines in ParmEd. 

I cannot reproduce this locally but I suspect that this issue might be related to using an old version of git.

Could you post  the output of `git --version`?

**Comment by Marcela51** [comment]
git version 1.7.1

I cannot remember how I fixed it before. You had told me to comment
out some lines but I did not. 

Marcela

**Comment by Marcela51** [comment]
Do I have to comment out the lines myself? I do not see source code in 
/usr/local/packages/python/2.7.8/lib/python2.7/site-packages
or do I just install parmed again?

Marcela

**Comment by ctk3b** [comment]
You should only have to comment these out and replace them with something like 

`__version__ = '2.6.1'`

https://github.com/ParmEd/ParmEd/blob/master/parmed/__init__.py#L17-L19

**Comment by ctk3b** [comment]
If you can easily do it, simply updating git might be the better fix but I don't know if that is what's causing the issue for certain. It is a very old version of git though and the failure occurs in a piece of code that attempts to extract something from a git command line output.

**Comment by ctk3b** [comment]
Also to clarify, since you installed parmed as editable, you only need to make this change in the source code that you downloaded.

**Comment by Marcela51** [comment]
Done. Thanks a lot. Commenting out the lines works. 

Marcela
