### ISSUE TITLE
Dihedral9_vacuum gromacs to gromacs unit test now failing

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/InterMol#295]
The energy is -233.957, where it should of course be near zero.
 
the dihedral9_vacuum to gromacs to desmond test has the same error, but it's of the same magnitude.

Probably should be implementing CI so this gets caught immediately. 

Some regression seems to indicate that it was introduced in:

commit dad2ec758ae402966cb98d7c4bb24c696b1af1c9
Author: Christoph Klein <christoph.t.klein@me.com>
Date:   Tue Nov 22 15:17:01 2016 -0600

    Add case of dihedral wild cards in gromacs (#287)
    
    Additionally
    * Raise proper warning when dihedral lookups fail
    * Fix deprecation warning in logging module
    * Add stress test of charmm FF in gromacs format

Christoph, I will be traveling today -- can you take a look?

**Comment by ctk3b** [comment]
I'll get to it this afternoon.
