### ISSUE TITLE
Tilt factors ignored when converting from GROMACS to LAMMPS

### ISSUE THREAD

**Issue by nabraham47** [shirtsgroup/InterMol#357]
If tilt factors are present in the .gro file they do not show up when converting the system to LAMMPS.

**Comment by mrshirts** [comment]
By tilt factors, you mean the off diagonal elements (last 6 components) in the box vector in the .gro file?

Can you give an example for what the output should be for LAMMPS in this scenario (as well as what it is now?)

**Comment by nabraham47** [comment]
Yes, LAMMPS refers to them as the tilt factors in their nomenclature. 
For example, the final line in the .gro file for one of my systems is:
  2.7102121  2.5401599  2.3915862  0.0000000  0.0000000  0.0000000  0.0000000 -0.4855272  0.0000000

The .input file from InterMol has the box defined in the .lmp file as:
-17.1176747   9.9844466 xlo xhi
-13.8512351  11.5503637 ylo yhi
-12.4969379  11.4189243 zlo zhi

What it should be is:
-17.1176747   9.9844466 xlo xhi
-13.8512351  11.5503637 ylo yhi
-12.4969379  11.4189243 zlo zhi
0.0 -4.855272 0.0 xy xz yz

**Comment by mrshirts** [comment]
Got it.  That should be relatively easy to fix, out of time now but hopefully can look at it tonight.
