### ISSUE TITLE
Issue with parmed.utils.six

### ISSUE THREAD

**Issue by samuele-giannini** [shirtsgroup/InterMol#377]
Hi All, sorry to disturb. I have a problem running InterMol:
python convert.py --des_in validation/inputs/Desmond/UnitTest/frag_opls2001/frag_opls2001.cms --gromacs --odir test_output -e
Traceback (most recent call last):
  File "convert.py", line 10, in <module>
    from parmed.utils.six import string_types
ModuleNotFoundError: No module named 'parmed.utils.six'

I did a bit of googling but cannot find a way to install parmed.utils.six. 
Any help would be appreciated.
Sam

**Comment by AxillaryPower** [comment]
I came here to ask about the same issue; it appears that newer versions of ParmEd no longer have parmed.utils.six in its utils folder, where evidently it used to. InterMol (or at least convert.py) may need to be updated to be compatible with more recent ParmEd.

**Comment by mattwthompson** [comment]
I have a fix running in #380 but  if you're using a local build, you should be able to modify line 10 in `intermol/convert.py` to just be `from six import string_types` to get it running again. That module in ParmEd is copy-pasted from another one that's probably installed in every Python environment these days.

**Comment by mattwthompson** [comment]
To any future travelers sent here by the Google machine: this should be fixed in the `master` branch via the linked PR. That change will also go into a release and conda package at some point.
