### ISSUE TITLE
Installing via easy_install vs. development: good workaround strategy?

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/InterMol#72]
So, one thing I realized is that if intermol is installed using the setup.py script, then these files end up superseding any locally developed version. 

I.e. even if you have PYTHONPATH set up to point to your local version, it will always use the installed version first.  

This is an issue with helium, where we have several people developing intermol (because that's where we have gromacs/desmond/lammps all installed).  You can't keep installing, because then it will affect the version other people can actually run.

This may explain some issues with Jacob not able to replicate Christoph's commits.

I haven't been able to come up with a perfect answer.  People generally recognize this is a problem with easyinstall.
http://stackoverflow.com/questions/5984523/eggs-in-path-before-pythonpath-environment-variable

My current workaround is to edit the startup script:

/usr/local/lib/python2.7/site-packages/sitecustomize.py
to be

  import sys
  import os
  sys.path = [''] + os.environ['PYTHONPATH'].split(':') + sys.path

This seems to solve the problem for users of helium.

This requires that the intermol directory is included in $PYTHONPATH

**Comment by ctk3b** [comment]
Deleting your installed version and doing `python setup.py develop` is the fix for this although doing this inside a virtualenv is even better.
